// Update the Testimonial interface to include Hindi text
export const testimonialData = [
  {
    id: 1,
    name: "Praharsh Patel",
    location: "Ahmedabad",
    text: "Kundali matching gave the right direction to our relationship, and today we are living a happy married life. Thank you Sandeep ji!",
    textHi: "कुंडली मिलान से हमारे रिश्ते की सही दिशा मिली, और आज हम खुशहाल विवाहित जीवन जी रहे हैं। धन्यवाद संदीप जी!",
    rating: 5,
    category: "Kundali Matching",
    featured: true,
  },
  {
    id: 2,
    name: "Hardik Joshi",
    location: "Vadodara",
    text: "I got peace from Kalsarp Dosh through online puja. Now there is stability and positivity in life.",
    textHi: "ऑनलाइन पूजा से मुझे कालसर्प दोष की शांति मिली। अब जीवन में ठहराव और सकारात्मकता है।",
    rating: 5,
    category: "Remedies",
  },
  {
    id: 3,
    name: "Bharatbhai Patel",
    location: "Mumbai",
    text: "I ordered gemstones from Sandeep ji and after wearing them, there was a tremendous change in my career.",
    textHi: "संदीप जी से रत्न मंगवाया और पहनने के बाद करियर में जबरदस्त बदलाव आया।",
    rating: 5,
    category: "Gemstones",
    featured: true,
  },
  {
    id: 4,
    name: "Kalpeshbhai Jadav",
    location: "Rajkot",
    text: "I was continuously incurring losses in my business, now I am making profits with his advice.",
    textHi: "व्यवसाय में लगातार घाटा हो रहा था, अब उनकी सलाह से मुनाफा होने लगा है।",
    rating: 5,
    category: "Business",
  },
  {
    id: 5,
    name: "Kamlesh Parekh",
    location: "Surat",
    text: "There were cracks in our relationship, but with his horoscope advice, the love between us returned.",
    textHi: "रिलेशनशिप में दरारें थी, पर उनकी कुंडली सलाह से हमारे बीच का प्रेम फिर से लौट आया।",
    rating: 5,
    category: "Relationships",
  },
  {
    id: 6,
    name: "Miloni Shah",
    location: "Germany",
    text: "My dream of studying abroad came true with his guidance.",
    textHi: "विदेश पढ़ाई का सपना उनका मार्गदर्शन मिलने से साकार हो गया।",
    rating: 5,
    category: "Education",
    featured: true,
  },
  {
    id: 7,
    name: "Nagesh",
    location: "Nashik",
    text: "I used to earn money but the money did not stay, now I have both peace and savings.",
    textHi: "कमाई तो होती थी लेकिन पैसे रुकते नहीं थे, अब शांति और सेविंग्स दोनों हैं।",
    rating: 5,
    category: "Finance",
  },
  {
    id: 8,
    name: "Hitesh Chauhan",
    location: "Bhavnagar",
    text: "I had a dream of buying my own house, with his Kundali advice, I have done Grihapravesh of my house today.",
    textHi: "खुद का घर लेने का सपना था, उनकी कुंडली सलाह से आज अपने घर में गृह प्रवेश कर चुके हैं।",
    rating: 5,
    category: "Property",
  },
  {
    id: 9,
    name: "Reena Soni",
    location: "Baroda",
    text: "There used to be quarrels in the whole family, now there is an atmosphere of peace and love.",
    textHi: "पूरे परिवार में झगड़े रहते थे, अब शांति और प्रेम का माहौल है।",
    rating: 5,
    category: "Family",
  },
  {
    id: 10,
    name: "Jyoti Thakur",
    location: "Delhi",
    text: "The facility of online Muhurta and Puja saved both time and energy.",
    textHi: "ऑनलाइन मुहूर्त और पूजा की सुविधा ने समय और ऊर्जा दोनों बचाई।",
    rating: 5,
    category: "Online Services",
  },
  {
    id: 11,
    name: "Neha Sharma",
    location: "Jaipur",
    text: "I got pure and proven gemstones, results started showing immediately.",
    textHi: "रत्न शुद्ध और सिद्ध मिला, परिणा�� तुरंत दिखने लगे।",
    rating: 5,
    category: "Gemstones",
  },
  {
    id: 12,
    name: "Mitul Parmar",
    location: "Surat",
    text: "Sandeep ji's words have both faith and solutions.",
    textHi: "संदीप जी की वाणी में विश्वास और समाधान दोनों हैं।",
    rating: 5,
    category: "General",
  },
  {
    id: 13,
    name: "Meenakshi Khatik",
    location: "Udaipur",
    text: "I had only heard about astrology, now with his help I have also experienced it.",
    textHi: "ज्योतिष को मैंने केवल सुन रखा था, अब उनकी मदद से अनुभव भी किया।",
    rating: 5,
    category: "General",
  },
  {
    id: 14,
    name: "Ritika Desai",
    location: "Ahmedabad",
    text: "My marriage was getting stopped in my Kundali, now everything is fine and I also got good news.",
    textHi: "मेरी कुंडली में विवाह रुक रहा था, अब सब ठीक है और शुभ समाचार भी मिला।",
    rating: 5,
    category: "Marriage",
    featured: true,
  },
  {
    id: 15,
    name: "Amit More",
    location: "Pune",
    text: "I was not able to concentrate on studies, now I am able to concentrate and results are improving.",
    textHi: "पढ़ाई में ध्यान नहीं लग रहा था, अब मन लग रहा है और रिजल्ट बेहतर हो रहे हैं।",
    rating: 5,
    category: "Education",
  },
  {
    id: 16,
    name: "Anil Pandya",
    location: "Surat",
    text: "I am surprised to see sudden progress in business, have experienced the miracle of gemstones.",
    textHi: "बिज़नेस में अचानक प्रगति देखकर अचंभित हूँ, रत्न का चमत्कार अनुभव किया है।",
    rating: 5,
    category: "Business",
  },
  {
    id: 17,
    name: "Bhavana Joshi",
    location: "Nagpur",
    text: "The experience of online puja was very good, the live darshan gave peace to the heart.",
    textHi: "ऑनलाइन पूजा का अनुभव बहुत अच्छा रहा, लाइव दर्शन से दिल को शांति मिली।",
    rating: 5,
    category: "Online Services",
  },
  {
    id: 18,
    name: "Harishbhai Shah",
    location: "Jamnagar",
    text: "There was a vastu defect in the house, now everything is going well.",
    textHi: "घर में वास्तु दोष था, अब सब कुछ ठीक चल रहा है।",
    rating: 5,
    category: "Vastu",
  },
  {
    id: 19,
    name: "Neha Patel",
    location: "Surat",
    text: "Sandip ji's team's behavior is very professional, got timely delivery and guidance.",
    textHi: "संदीप जी की टीम का व्यवहार बहुत प्रोफेशनल है, समय पर डिलीवरी और म���र्गदर्शन मिला।",
    rating: 5,
    category: "Service",
  },
  {
    id: 20,
    name: "Akash Roy",
    location: "Indore",
    text: "Relationship was on the verge of breaking, now preparing for marriage.",
    textHi: "रिश्ते टूटने की कगार पर थे, अब शादी की तैयारी कर रहे हैं।",
    rating: 5,
    category: "Relationships",
  },
  {
    id: 21,
    name: "Rohit Vyas",
    location: "Canada",
    text: "There were frequent obstacles in foreign travel, now got visa and flight date too!",
    textHi: "विदेश यात्रा में बार-बार रुकावटें आ रही थीं, अब वीज़ा भी मिल गया और फ्लाइट की डेट भी!",
    rating: 5,
    category: "Travel",
    featured: true,
  },
  {
    id: 22,
    name: "Bhavin Thakkar",
    location: "Baroda",
    text: "Money was not lasting, now regular savings are happening, due to correct identification of planets!",
    textHi: "पैसे टिक नहीं रहे थे, अब नियमित बचत हो रही है, ग्रहों की सही पहचान से!",
    rating: 5,
    category: "Finance",
  },
]